my_string = ('как вас зовут:')
print(type(my_string))
print(len(my_string))
print(str.upper(my_string))
print(str.lower(my_string))
print(my_string.replace(' ', ''))
print(str(my_string)[0])
print(my_string[-1])